language: ruby
install: gem install mdl awesome_bot
script:
  # - mdl -r ~MD013,~MD033 README.md
  - travis_wait 100 awesome_bot --allow-dupe --skip-save-results --allow-redirect --white-list researchgate.net,mi.eng.cam.ac.uk/~nm480/ --base_url https://github.com/Separius/awesome-sentence-embedding/blob/master/ README.md
